AllCops:
  SuggestExtensions: false

Layout/LineLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 32

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 16

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
